name: country_codes
description: Country codes is an helper package that provides country details given a particular localization, such as dial codes, ISO 3166 codes (alpha-2, alpha-3) and country names.
version: 3.1.0+2
homepage: https://github.com/miguelpruivo/country_codes

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.10.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.miguelruivo.flutter.plugin.countrycodes.country_codes
        pluginClass: CountryCodesPlugin
      ios:
        pluginClass: CountryCodesPlugin
